apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespace.yaml
  - manifests/portfolio-placeholder.yaml
  - manifests/portfolio-ingress.yaml
  - manifests/traefik-acme-config.yaml

configMapGenerator:
  - name: portfolio-html
    namespace: portfolio
    files:
      - index.html=site/index.html
