apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:N2R9rR4=,iv:gu9ZcibK1sIRLezDxWX5do1Kqat/KrxeItxXRtkIx0o=,tag:VW93yDcYnRUDdG31XsYZwA==,type:str]
    admin-password: ENC[AES256_GCM,data:0ZNgE+yyTq7On+oSnaq9OvnA0AHazLom,iv:nvCmE7tJjiiFA9YXHN8Lc7Vyd0heppjp/lRaE7CRxPY=,tag:7F1OVTV5ClD0Xg2njEJfqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18m6swtgz43aq44dvsrghh8yu7zltnc70uggwlvmdjsagax899q3sn73695
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTVZIWFNjYWF0M2t6YzBi
            amhFQjlDMU9EZGRBRUE2c3BEVHBIWlN0QW5VCk5lVk9Xd2kzakorUitDaS9CRng3
            NDBsalRXR0ZNaDlvb2tHQ0MxaHp5MWcKLS0tIGM5akN4UDcxWE9PN3dhRUY0Vlk5
            Tk80M3JseGNhUGU0UTc5TjhseDdqVWMKYTZMxw36YjISjDIYhz6gz18h82togSyJ
            /euDG11Q8uLKXRa9fMuTIz7q6jZjR22IvSpNeHR4OyF5vSXTEEs63A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T15:28:55Z"
    mac: ENC[AES256_GCM,data:9ZDChW55nqh/Yk+0CfXn5Vor2jq1jYcAA8J/vSV6hmN83dOnp6GGkJymyUwBPnLG+KxSeVP9KuXm49WxXXDeko6/5x5py9U76IMDq6ZJW3WvNdOYND/RoHrRw2UVJFinbNPj7vpQsIPatqUD94DoZSeVfnX9Uq0ODd6megBDFpw=,iv:g8SVZddb/eaMyzU53EfOPt0g9GiHdbM+SFi4/gUwIVA=,tag:TiBxQXIJRLOnJrtxvstdGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
