apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:cUG+Xxc=,iv:xzTSOoExE2ldi/wY/Ws4BVcSvQebqEC9uHUIVFxtLNM=,tag:IUizQKDo8G0EgVFvDxDNuA==,type:str]
    admin-password: ENC[AES256_GCM,data:H27BI9RAZE6/Iy8CdlWcUdn2rUJwNi92,iv:jbOTzPBbjt2MwPfxJwyGRlEVUWcj4l0C/t1+dVNc+6I=,tag:jpuxPQ2sUaIs9kGVoEyNEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wfjxcnwfedxan7ur9cs0u4h7wluq8s7vckr3stzecxnpk6r7jcds6exjst
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwc0dBNThPU0pGbzl6Uytm
            L1lVOVF2MWlqMFRoK3I0M25ZWDBJSkovZDNzCkFRMUVBSkRvTkpmM3NRdGd1VVBO
            WlNhSS8rUGtrWGpPK3BtK3A0NnFMeXMKLS0tICtOQVdJOUxMWkhPVUpiRDN0UlZu
            YXdSQTBIeVZwS0VZYURpWmF4SDJxa28K264aocHLYAb3JIxyVK43OouUEva6sFSp
            Wo3rLiJI8RHmAg7CvUxoGEnxu6iRGlt1nAZHRNpsI+kPewH36Ht01g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T15:39:31Z"
    mac: ENC[AES256_GCM,data:gAuD6AXHuVDSnd1nHImxqcj1S0TKWohsWgBIoDfjAT8aCZ1HjpVY2HaorilHNbSu0jn5SNLo0A+xiKVOm7eXoQbogV9q7zLphD/A3XLDclrlv2ZtklD6/jGC/PhWtF9h+Q6akk4ceKxZPAidIjfVNKtJO3coQFYxVttKm/exI6k=,iv:9WvzNHAGzCdxrMbKYlaNtTHHD2GP0aaFNKFRqPP8K3Q=,tag:BJ0F7GqveBKkFsm9U0DXug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
