apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - traefik-acme-config.yaml
  - rbac.yaml
  - monitoring/grafana-secret.enc.yaml
  - notifications/provider.yaml
  - notifications/alert.yaml
  - image-automation/image-repository.yaml
  - image-automation/image-policy.yaml
  - image-automation/image-update-automation.yaml
